### PR TITLE
Implement xstate-ninja-vue

### PR DESCRIPTION
**Pull request by Zehir**
Contribution for #7

@rlaffers Should I add my name as author for the `@xstate-ninja/vue` package ?

### CODE REVIEW

**Comment by Zehir** [comment]
Some screenshot of the example
image
image
image

**Comment by rlaffers** [comment]
> Contribution for #7
> 
> @rlaffers Should I add my name as author for the `@xstate-ninja/vue` package ?

Yes please.

**Comment by Zehir** [comment]
> > Contribution for #7
> > @rlaffers Should I add my name as author for the `@xstate-ninja/vue` package ?
> 
> Yes please.

Done @rlaffers thanks

**Comment by Zehir** [comment]
resolve #7

**Comment by Zehir** [comment]
Could you publish it on npm ?

**Comment by Zehir** [comment]
What do you think about a more generic way to register Ninja ?
```typescript
import type { AnyInterpreter } from 'xstate'

import createXStateNinjaSingleton from 'xstate-ninja'

const ninja = createXStateNinjaSingleton()

export function registerNinja(actor: AnyInterpreter) {
  return watchEffect((onCleanup) => {
    if (actor.options?.devTools) {
      ninja.register(actor)
      onCleanup(() => ninja.unregister(actor))
    }
  })
}

```
```typescript
const machine = useMachine(gatewayMachine, {
  id: `${gatewayMachine.id}-${id.value}`,
  devTools: true,
})

onScopeDispose(registerNinja(machine.service))
```
The `onScopeDispose` is a vue method to auto call the method when the vue who started the machine get deleted

There is still some vue related method in the register method but we can extract them out too

**Review by rlaffers — APPROVED** [review]
@Zehir Looks great. Thank you! :heart:

**Pull request merged**
